config/routes.rb
Rails.application.routes.draw do  get 'microposts/index'
  resources :posts
  resources :sessions
  resources :users
  root                    'dashboard#index'
  get   'mainboard'   =>  'dashboard#mainboard'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get   'sign_up'  => 'users#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  include SessionsHelper
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        @posts = Post.all.order("created_at desc")
        @paginatedPost = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
    end
    
    def mainboard
        @userPosts = Post.where(user_id: params[:user_id]).order("created_at desc").paginate(page: params[:page], per_page: 5)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @allPosts = Post.all
  end

  def showname
    @user = User.find(params[:id]).name
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to :controller => 'dashboard', :action => 'index'  , notice: 'Post was successfully created.' }
        format.json { render :application, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to :controller => 'dashboard', :action => 'index', notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'dashboard', :action => 'index', notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new'
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      # Create an error message.
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the CompanyDashboard!"
       redirect_to :controller => 'dashboard', :action => 'index'
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Daniel Koprowski"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def all
    posts.index
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
    <%= render 'layouts/posts' %>

app/views/dashboard/mainboard.html.erb
  <div class="postbox">
  <div class="postContainer">
    <div class="text-center">
      <div class="well">
        <h4><%= @userPosts.first.user.name %> posts:</h4>
        <hr data-brackets-id="12673">
        <ul data-brackets-id="12674" id="sortable" class="list-unstyled ui-sortable">   
          <% @userPosts.each do |post| %>
              <strong class="pull-left primary-font"><%= post.user.name %></strong>
                <small class="pull-right text-muted">
                 <% if logged_in? %>
                     <% if current_user.id == post.user_id %>
                       <span class="glyphicon glyphicon-remove"></span>
                       <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  <% end %>
                 </small>
              <br>
              <li class="ui-state-default"><%= post.content %></li>
              <br>
      
          <% end %>
          <%= will_paginate @userPosts %>
        </ul>
      </div>
    </div>
  </div>
  </div>

app/views/layouts/_footer.html.erb
<footer>
  <center>Daniel Koprowski</center>

</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <%= link_to "Companies dashboard", root_path, id: "logo", class:"btn btn-default"  %>

            
          <ul class="nav navbar-nav navbar-right vcenter">
              <% if current_user %>
                <li class="loggedmail vcenter">Logged in as <%= current_user.email %></li>
                <li><%= link_to "Log out", logout_path, method:"delete", class:"btn btn-default right" %></li>
                
              <% else %>
                <li><%= link_to "Register now!", 'sign_up', class: "btn btn-lg btn-primary" %></li>
                <li><%= link_to "Log in", login_path , class:"btn btn-default right"%></li>
                
              <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_posts.html.erb
<div class="postbox">
  <h1>Listing Posts</h1>
  <!--
  <table>
    <thead>
      <tr>
        <th>Content</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.content %></td>
          <td><%= post.user_id %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  -->
  <div class="postContainer">
    <div class="text-center">
      <div class="well">
        <h4>What is on your mind?</h4>
        <p id="notice"><%= notice %></p>
        <div class="input-group">
          
          <% if logged_in? %>
            <%= form_for(@posts.new) do |f| %>
            <span class="input-group-btn" onclick="addComment()"> 
              <%= f.text_field :content, :id =>'userComment', :class => 'form-control input-sm chat-input', :placeholder => 'Write your message here...'%>
              
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= button_tag(type: 'submit', class: "btn btn-primary btn-sm") do %> <span class="glyphicon glyphicon-comment"></span>Add Comment <% end %>
              </span>
            <% end %>
          <%end%>
          
        </div>
        <hr data-brackets-id="12673">
        <ul data-brackets-id="12674" id="sortable" class="list-unstyled ui-sortable">   
          <% @paginatedPost.each do |post| %>
              <strong class="pull-left primary-font">
                <a href="/mainboard?page=1&user_id=<%= post.user_id %>"><%= post.user.name %></a>
              </strong>
                <small class="pull-right text-muted">
                 <% if logged_in? %>
                     <% if current_user.id == post.user_id %>
                       <span class="glyphicon glyphicon-remove"></span>
                       <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  <% end %>
                 </small>
              <br>
              <li class="ui-state-default"><%= post.content %></li>
              <br>
      
          <% end %>
          <%= will_paginate @paginatedPost %>
            <!--
              <strong class="pull-left primary-font">James</strong>
              <small class="pull-right text-muted">
                 <span class="glyphicon glyphicon-time"></span>7 mins ago</small>
              </br>
              <li class="ui-state-default">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </li>
              </br>
               <strong class="pull-left primary-font">Taylor</strong>
              <small class="pull-right text-muted">
                 <span class="glyphicon glyphicon-time"></span>14 mins ago</small>
              </br>
              <li class="ui-state-default">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
              -->
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  
  
  <%= yield %>

    <%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if logged_in? %>
    ZALOGOWANY
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.number_field :user_id, :value => current_user.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% else %>
    NIEZALOGOWANY
  <% end %>


<% end %>

app/views/posts/_index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="container">
  <div class="col-lg-4 col-sm-6 text-center">
    <div class="well">
      <h4>What is on your mind?</h4>
      <div class="input-group">
          <input type="text" id="userComment" class="form-control input-sm chat-input" placeholder="Write your message here..." />
  	    <span class="input-group-btn" onclick="addComment()">     
              <a href="#" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-comment"></span>Add Comment</a>
          </span>
      </div>
      <hr data-brackets-id="12673">
      <ul data-brackets-id="12674" id="sortable" class="list-unstyled ui-sortable">    
        <% @posts.each do |post| %>
            <strong class="pull-left primary-font"><%= post.user_id %></strong>
                    <small class="pull-right text-muted">
               <span class="glyphicon glyphicon-time"></span>7 mins ago</small>
            </br>
            <li class="ui-state-default"><%= post.content %></li>
            </br>
    
        <% end %>
          <!--
            <strong class="pull-left primary-font">James</strong>
            <small class="pull-right text-muted">
               <span class="glyphicon glyphicon-time"></span>7 mins ago</small>
            </br>
            <li class="ui-state-default">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </li>
            </br>
             <strong class="pull-left primary-font">Taylor</strong>
            <small class="pull-right text-muted">
               <span class="glyphicon glyphicon-time"></span>14 mins ago</small>
            </br>
            <li class="ui-state-default">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
            -->
      </ul>
    </div>
  </div>
</div>
<%= link_to 'New Post', new_post_path %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h2>Sign up</h2>
<%= form_for(@user) do |f| %>

<div class="row">
<div class="col-md-3 ">
<div class="field">
<%= f.label :name %>
<%= f.text_field :name, :class => "form-control" %>
</div>
<div class="field">
<%= f.label :email %>
<%= f.email_field :email, :class => "form-control"%>
</div>
<div class="field">
<%= f.label :password %>
<%= f.password_field :password, :class => "form-control" %>
</div>
<div class="field">
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, :class => "form-control"%>
</div>
<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>
</div>
</div>